### ISSUE TITLE
Make blobvault PVC storage optional, if S3 bucket is used 

### ISSUE THREAD

**Issue by mjasion** [iterative/helm-charts#145]
In #82 we introduced the local baking store to fix issues with Minio (missing path based routing). Delivering the change we started deploying `nginx` container, which was mounting the PVC volume `blobvault` attached to `worker` pod.

```mermaid

C4Dynamic
    ContainerDb(c1, "blobvault", "PVC")
    Container_Boundary(B, "Worker") {
      Container(c2, "Worker Pod")
    }
    Container_Boundary(c, "Nginx Pod",) {
      Container(c3, "Nginx")
    }
    Rel(c2, c1, "")
    Rel(c1, c3, "")

```

```[tasklist]
### Tasks
- [x] Make optional PVC volume if S3 bucket is used
- [x] Replace nginx helm-chart with nginx deployment
- [x] Add Nginx sidecar to backend pod, if `basePath` is configured  for non `/`
- [x] Do not deploy nginx if pvc is not deployed
- [ ] ~Validate if more than 1 worker is created to use S3 bucket~
- [x] Do not deploy ingress for `/blobvaul` if the nginx is not deployed too
```

**Comment by jesper7** [comment]
> Validate if more than 1 worker is created to use S3 bucket

Can you elaborate on this one?

**Comment by mjasion** [comment]
> > Validate if more than 1 worker is created to use S3 bucket
> 
> Can you elaborate on this one?
@jesper7 

Not every cluster has the storageClass which chan be attached to multiple nodes. Scaling `worker` means that they will run on the different node, but pvc cannot be attached then.

I realized the issue on EKS, when I deployed the Studio. When I scaled up workers, there were scheduled to different node but PVC was attached to the 1st one.
